server:
  port: 9000

spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: off

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_practise
    username: exist
    password: admin
    driver-class-name: org.postgresql.Driver
  main:
    banner-mode: off

logging:
  level:
    org:
      springframework:
        data: warn
        security: trace
      hibernate: warn
    root: warn
    org.springframework.security.web.FilterChainProxy: trace

jwt:
  secret: vcNreNuHt307dFou/OD1Uc3w97+sLcJpi0nBsWbNK5czapXowy++EDOBbJ6AVBj1e+CxDL4d2M8YZlV5KNu2UA==
  expiration-ms: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka